<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $product = [
            /* Nike */
            ['STUSSY X AIR ZOOM SPIRIDON CAGED 2 FOSSIL', 2800000, 20, 1, 1, 'product-1.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AMBUSH X AIR FORCE 1 LOW BLACK', 3300000, 25, 2, 1, 'product-2.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AMBUSH X AIR FORCE 1 LOW PHANTOM', 3300000, 20, 1, 1, 'product-3.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['WMNS AIR JORDAN 1 LOW SE REVERSE ICE BLUE', 1900000, 15, 2, 1, 'product-4.png', 'lam', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['SB X AIR JORDAN 4 RETRO SP PINE GREEN', 3300000, 10, 1, 1, 'product-5.png', 'xanh', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['TRAVIS SCOTT X AIR JORDAN 1 RETRO LOW OG OLIVE', 3500000, 30, 1, 1, 'product-6.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR JORDAN 1 RETRO HIGH OG CHICAGO LOST & FOUND', 3200000, 20, 2, 1, 'product-7.png', 'đỏ', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR MAX 97 SUMMIT WHITE BLACK', 2000000, 25, 1, 1, 'product-8.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR FORCE 1 07 ESSENTIAL WHITE BLACK GOLD', 1700000, 20, 1, 1, 'product-9.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR FORCE 1 WHITE LIGHT SILVER', 1700000, 20, 1, 1, 'product-10.png', 'bạc', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR FORCE 1 ESSENTIAL LOW WHITE GYM RED', 1700000, 20, 1, 1, 'product-11.png', 'đỏ', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR FORCE 1 LOW ORANGE PAISLEY', 1700000, 20, 2, 1, 'product-12.png', 'cam', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR JORDAN 1 LOW SE BEADED SWOOSH', 1900000, 10, 1, 1, 'product-13.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR JORDAN 1 LOW SE CONCORD', 1900000, 10, 1, 1, 'product-14.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['AIR JORDAN 1 MID SE DIAMOND', 2500000, 30, 2, 1, 'product-15.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Nike Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            /* Adidas */
            ['ULTRA BOOST 6.0 BLACK CAMO', 1800000, 30, 1, 2, 'product-16.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['ULTRABOOST 4.0 DNA BLACK GREEN WHITE', 1800000, 30, 1, 2, 'product-17.png', 'xanh', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['SAMBA VEGAN WHITE', 1200000, 20, 1, 2, 'product-18.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['YEEZY BOOST 700 MAGNET', 2800000, 30, 2, 2, 'product-19.png', 'xám', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['YEEZY 500 BONE WHITE', 2500000, 30, 2, 2, 'product-20.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['SUPERSTAR WHITE SILVER METALLIC', 1300000, 10, 1, 2, 'product-21.png', 'bạc', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['ULTRABOOST 22 HEAT.RDY BLACK CLEAR ORANGE', 1900000, 20, 1, 2, 'product-22.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['ULTRABOOST 22 HEAT.RDY WHITE TURBO', 1900000, 20, 1, 2, 'product-23.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['ULTRABOOST 22 NON DYED BLACK', 1900000, 20, 2, 2, 'product-24.png', 'xám', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['YEEZY 700 STATIC', 2800000, 30, 1, 2, 'product-25.png', 'xám', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['YEEZY 700 WAVE RUNNER', 2800000, 30, 2, 2, 'product-26.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['YEEZY BOOST 700 WASH ORANGE', 2800000, 30, 1, 2, 'product-27.png', 'cam', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['YEEZY BOOST 700 UTILITY BLACK', 2800000, 30, 2, 2, 'product-28.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['EQ21 RUN COLD.RDY', 1100000, 10, 2, 2, 'product-29.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['EQ21 RUN BLACK RED', 1100000, 10, 1, 2, 'product-30.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            /* Vans */
            ['VANS STYLE 36 RED', 1100000, 10, 1, 3, 'product-31.png', 'đỏ', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS VAULT STYLE 36 BLACK', 1250000, 20, 1, 3, 'product-32.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS OLD SKOOL CLASSIC BLACK', 1250000, 30, 1, 3, 'product-33.png', 'đen', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS VAULT STYLE 36 - RED', 950000, 10, 2, 3, 'product-34.png', 'đỏ', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS VAULT STYLE 36 - BLUE', 1150000, 20, 1, 3, 'product-35.png', 'lam', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS OLD SKOOL CLASSIC NAVY', 950000, 10, 1, 3, 'product-36.png', 'lam', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS FOG X ERA 95 REISSUE MARSHMALLOW', 1200000, 20, 1, 3, 'product-37.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS FOG X ERA 95 DX COLLECTION 2 WHITE', 1200000, 20, 2, 3, 'product-38.png', 'trắng', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS FOG X ERA 95 DX COLLECTION 2 RED', 1200000, 20, 1, 3, 'product-39.png', 'đỏ', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
            ['VANS STYLE 36 BLUE', 1000000, 20, 2, 3, 'product-40.png', 'lam', 1, 1, 'Với thiết kế kiểu dáng đẹp và thể thao, Adidas Air Max AP cho phép bạn kết nối quá khứ và hiện tại với sự thoải mái hạng nhất. Các chi tiết di sản lóe lên phù hợp với Air Max 97, trong khi phần trên được sắp xếp hợp lý và đế giữa hỗ trợ mang lại cho nó một góc cạnh hiện đại khó cưỡng lại. Air Max AP cũng có thiết kế cấu hình thấp và cổ áo có đệm, sang trọng mang lại sự thoải mái A+, trong khi lưới thoáng khí và đế đệm có thể mặc được và bất kể bạn làm gì trong ngày!', 1],
        ];

        foreach($product as $product){
            Product::create([
                'name' => $product[0],
                'price' => $product[1],
                'discount' => $product[2],
                'category_id' => $product[3],
                'brand_id' => $product[4],
                'image' => $product[5],
                'color' => $product[6],
                'status' => $product[7],
                'featured' => $product[8],
                'description' => $product[9],
                'active' => $product[10]
            ]);
        }
    }
}
